language: scala

scala:
- 2.11.1

jdk:
- oraclejdk7

branches:
  only:
  - master
  # scala-2.9
  # scala-2.10

script:
- sbt ++$TRAVIS_SCALA_VERSION clean test

after_success:
- sbt ++$TRAVIS_SCALA_VERSION clean publish

env:
  global:
  # travis encrypt -r stacycurl/pimpathon SONATYPE_USERNAME=<USERNAME>
  - secure: "GtMoVDw4EdbHc1TKyinx4BbtvtiyZWp0DS5fi6tUNzrqajihpj0d6sxPLMupYyKJnQtBZBpLmxtrfRmyeIyuS3Oz1OkapHy06grLJl4Eb1fHmi5OwcDY/Q96E2mFdR2a4NH0WZ596gxUvmT26DXVsDyvbJFhgCGqhYDV8BKD9l8="
  # travis encrypt -r stacycurl/pimpathon SONATYPE_PASSWORD=<PASSWORD>
  - secure: "OaekiCfTPKOCzTvxj9dbKDelmwIScYmuATNZ+2qJ/ilJTkBvsPdJJFoeMpDDC6/Z+43UZfVreU23Gkh8NidLaGO9KbqmD8si64nPrO8UVyUv9vn36tviseDAN8HAzxM8Mt9YC+sx5Z5v1ZhYLmXg6c1PoQgWrURG2uNsZe+BGJw="
